[package]
name = "flutter_tool"
version = "0.4.1"
edition = "2021"
license = "MIT"
publish = false

[workspace]
resolver = "2"
members = ["crates/flutter-models"]
exclude = ["crates/flutter-toolchain"]

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = "s"
panic = "abort"

[dependencies]
extism-pdk = "=1.4.1"
proto_pdk = "=0.35.5"
schematic = { version = "=0.20.6", default-features = false, features = ["schema"] }
serde = "1.0.229"
serde_norway = "0.9.42"
flutter_models = { path = "crates/flutter-models" }

[features]
default = ["wasm"]
wasm = []
live-tests = []

[dev-dependencies]
proto_pdk_test_utils = "=0.50.2"
starbase_sandbox = "0.12.0"
tokio = "1.52.0"
