name: example_mobile_app
description: Flutter application for the Flutter monorepo example.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  example_core: ^0.1.0
  example_ui: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
